Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -2,18 +2,12 @@ name: C/C++ CI
 
 on:
   push:
-    branches: 
-      - branchMake
-      - branchAutomake
-      - branchAutoPackage
-      - branchAutoTest
-  pull_request:
     branches:
       - branchMake
       - branchAutomake
       - branchAutoPackage
       - branchAutoTest
-  workflow_dispatch:
+  pull_request:
     branches:
       - branchMake
       - branchAutomake
@@ -28,13 +22,16 @@ jobs:
     - uses: actions/checkout@v4
     - name: Install dependencies
       run: sudo apt-get install -y automake autoconf g++ make
-
-    - name: Generate configure script
-      if: github.ref == 'refs/heads/branchAutomake' || github.ref == 'refs/heads/branchAutoPackage' || github.ref == 'refs/heads/branchAutoTest'
+    - name: Generate configure script and Makefile.in
+      if: github.ref == 'refs/heads/branchAutomake' || github.ref == 'refs/heads/branchAutoPackage'
       run: aclocal && automake --add-missing && autoconf
-
+    - name: Check if Makefile.am exists
+      run: |
+        if [ ! -f "Makefile.am" ]; then
+          echo "Error: Makefile.am is missing!"
+          exit 1
+        fi
     - name: Run configure script
       run: ./configure
-
     - name: Build the project
       run: make
